### ISSUE TITLE
Uploading data to S3 via Istio using HTTP 2 fails with AWS_ERROR_HTTP_RST_STREAM_RECEIVED

### ISSUE THREAD

**Issue by vm-cyber** [awslabs/aws-c-http#495]
### Describe the bug

Uploading data to S3 via Istio using HTTP 2 fails with AWS_ERROR_HTTP_RST_STREAM_RECEIVED. This works when using HTTP 1.1.

Also I reproduce this problem with your elasticurl sample app. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Data should be successfully uploaded to S3 via Istio using HTTP 2

### Current Behavior

Uploading data to S3 via Istio using HTTP 2 fails with AWS_ERROR_HTTP_RST_STREAM_RECEIVED

```
[ERROR] [2024-12-03T11:11:39Z] [000000016d6f7000] [http-stream] - id=1 connection=0x12f008200 state=HALF_CLOSED_LOCAL: Peer terminated stream with HTTP/2 RST_STREAM frame, error-code=0x1(PROTOCOL_ERROR)
[TRACE] [2024-12-03T11:11:39Z] [000000016d6f7000] [http-stream] - id=1 connection=0x12f008200 state=CLOSED: Received RST_STREAM code=0x1(PROTOCOL_ERROR). State -> CLOSED
[ERROR] [2024-12-03T11:11:39Z] [000000016d6f7000] [http-stream] - id=1 connection=0x12f008200 state=CLOSED: Stream completed with error 2077 (AWS_ERROR_HTTP_RST_STREAM_RECEIVED).

```

This is  elasticurl logs:
[elasticurl.txt](https://github.com/user-attachments/files/18012313/elasticurl.txt)

Curl successfully uploaded the data with the same parameters. This is  curl logs:
[curl.txt](https://github.com/user-attachments/files/18012637/curl.txt)

### Reproduction Steps

elasticurl --verbose TRACE --method PUT --data-file <data-file> --header "content-encoding:deflate" --header "content-type:text/plain" --header "x-amz-meta-<sample header>" <presigned url>

### aws-c-http version used

v0.9.0

### Compiler and version used

Xcode 16.1

### Operating System and version

macOS 15.1.1

**Comment by TingDaoK** [comment]
Look through the logs from curl and CRT
Seems like CRT is sending out the first request right after the connection preface (which should be allowed according to the spec. 
https://httpwg.org/specs/rfc9113.html#preface). 

And looks like the server gets the preface and the first request, but reset the first request right after sending out the settings with protocol error. I cannot really tell what protocol error we have from the log. The possibilities I can think of maybe that the lstio server don't support get the request before the setting was acknowledged? 

I am not sure how curl does it, the log doesn't seem to have enough info of the details about how the connection established.

I would suggest firstly get some server side log if possible? Otherwise, is there any way for us to reproduce the issue? We cannot reach to your endpoint https://files-nightly.epmdev.be/, so that we cannot really reproduce this issue on our end

**Comment by jmklix** [comment]
Currently S3 doesn't support HTTP2. I'm not sure if this would be changing anytime soon, so best recommendation is to just just http1.1. Please let us know if you have any questions concerning this or any other parts of this sdk
